[plugin-azure-data-factory] Fix NPE introduced by changes in Azure SDK (#2998)
Exception stack-trace:

java.lang.NullPointerException: 'from' cannot be null.
  at java.base/java.util.Objects.requireNonNull(Objects.java:246)
  at com.azure.core.util.CoreUtils.mergeContexts(CoreUtils.java:367)
  at com.azure.resourcemanager.datafactory.implementation.DataFactoryManagementClientImpl.mergeContext(DataFactoryManagementClientImpl.java:445)
  at com.azure.resourcemanager.datafactory.implementation.PipelinesClientImpl.createRunWithResponseAsync(PipelinesClientImpl.java:1036)
  at com.azure.resourcemanager.datafactory.implementation.PipelinesClientImpl.createRunWithResponse(PipelinesClientImpl.java:1191)
  at com.azure.resourcemanager.datafactory.implementation.PipelinesImpl.createRunWithResponse(PipelinesImpl.java:100)
  at org.vividus.azure.datafactory.steps.DataFactorySteps.runPipeline(DataFactorySteps.java:111)