[tests] Update device for BrowserStack Android native tests (#6034)
* [tests] Update device for BrowserStack Android native tests

Google Pixel 4 is deprecated:

org.openqa.selenium.WebDriverException: [BROWSERSTACK_DEPRECATED_DEVICE_ERROR] The device google pixel 4-10.0 has been deprecated from 18 July 2025 onwards. Going forward any tests on device google pixel 4-10.0 will not be supported on BrowserStack. We strongly recommend you update your test scripts. For the current list of supported devices on BrowserStack, please check here - https://www.browserstack.com/list-of-browsers-and-platforms/app_automate

* [tests] Use Pixel 6 instead of Pixel 9

We need to use Google Pixel 6 because higher versions of Pixel-s do not support log capturing:

com.browserstack.client.exception.BrowserStackException: 400 Bad Request
GET https://api-cloud.browserstack.com/app-automate/builds/e83932d0b1e25ce5f9474ec599a8aee7733dcb18/sessions/1246877c3a08a9aed7e532b46718f07cc2ef7957/networklogs
{"status":400,"message":"[BROWSERSTACK_NETWORK_LOGS_NOT_CAPTURED] Your app is not configured to view network logs on this device. Please follow our \u003ca href='https://www.browserstack.com/docs/app-automate/appium/troubleshooting/networklogs-acceptinsecurecerts-issues'\u003etroubleshooting guide\u003c/a\u003e to configure your app. If error persists, reach out to support."}