[tests] Fix execution of integration tests on Windows (#2354)
Paths on Windows contain backslash \ which is an escape character for Groovy single-quoted strings, it causes errors like:
```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script1.groovy: 1: Unexpected character: '\'' @ line 1, column 35.
   def files = java.nio.file.Path.of('D:\a\vividus\vividus\vividus-tests\output/screenshots').toFile()?.listFiles(); return files?.length?:0
                                     ^

1 error
```

The solution is to use dollar slashy string to avoid the necessity to escape backslashes and/or forward slashes