Use Google Pixel 6
We need to use Google Pixel 6 because higher versions of Pixel-s do not support log capturing:

com.browserstack.client.exception.BrowserStackException: 400 Bad Request
GET https://api-cloud.browserstack.com/app-automate/builds/e83932d0b1e25ce5f9474ec599a8aee7733dcb18/sessions/1246877c3a08a9aed7e532b46718f07cc2ef7957/networklogs
{"status":400,"message":"[BROWSERSTACK_NETWORK_LOGS_NOT_CAPTURED] Your app is not configured to view network logs on this device. Please follow our \u003ca href='https://www.browserstack.com/docs/app-automate/appium/troubleshooting/networklogs-acceptinsecurecerts-issues'\u003etroubleshooting guide\u003c/a\u003e to configure your app. If error persists, reach out to support."}