[tests] Update device for BrowserStack Android native tests
Google Pixel 4 is deprecated:

org.openqa.selenium.WebDriverException: [BROWSERSTACK_DEPRECATED_DEVICE_ERROR] The device google pixel 4-10.0 has been deprecated from 18 July 2025 onwards. Going forward any tests on device google pixel 4-10.0 will not be supported on BrowserStack. We strongly recommend you update your test scripts. For the current list of supported devices on BrowserStack, please check here - https://www.browserstack.com/list-of-browsers-and-platforms/app_automate