[CI] Fix build on Windows Server 2022
The issue details (https://github.com/vividus-framework/vividus/runs/5231540487?check_suite_focus=true):
```
> Task :vividus-plugin-parquet:test

ConvertCsvToParquetFileExpressionProcessorTests > testConvertCsvToParquetFileExpression(String) > org.vividus.expression.ConvertCsvToParquetFileExpressionProcessorTests.testConvertCsvToParquetFileExpression(String)[1] FAILED
    java.io.UncheckedIOException: Problem during file interaction:
        at app//org.vividus.expression.ConvertCsvToParquetFileExpressionProcessor.evaluateExpression(ConvertCsvToParquetFileExpressionProcessor.java:73)
        at app//org.vividus.expression.ConvertCsvToParquetFileExpressionProcessor.evaluateExpression(ConvertCsvToParquetFileExpressionProcessor.java:41)
        at app//org.vividus.expression.AbstractExpressionProcessor.execute(AbstractExpressionProcessor.java:38)
        at app//org.vividus.expression.ConvertCsvToParquetFileExpressionProcessorTests.testConvertCsvToParquetFileExpression(ConvertCsvToParquetFileExpressionProcessorTests.java:53)

        Caused by:
        ExitCodeException exitCode=-1073741515:
            at app//org.apache.hadoop.util.Shell.runCommand(Shell.java:1008)
            at app//org.apache.hadoop.util.Shell.run(Shell.java:901)
            at app//org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:1213)
            at app//org.apache.hadoop.util.Shell.execCommand(Shell.java:1307)
            at app//org.apache.hadoop.util.Shell.execCommand(Shell.java:1289)
            at app//org.apache.hadoop.fs.RawLocalFileSystem.setPermission(RawLocalFileSystem.java:978)
            at app//org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileOutputStream.<init>(RawLocalFileSystem.java:324)
            at app//org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileOutputStream.<init>(RawLocalFileSystem.java:294)
            at app//org.apache.hadoop.fs.RawLocalFileSystem.createOutputStreamWithMode(RawLocalFileSystem.java:439)
            at app//org.apache.hadoop.fs.RawLocalFileSystem.create(RawLocalFileSystem.java:428)

            at app//org.apache.hadoop.fs.RawLocalFileSystem.create(RawLocalFileSystem.java:459)
4 tests completed, 2 failed
            at app//org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSOutputSummer.<init>(ChecksumFileSystem.java:433)
            at app//org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:521)
            at app//org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:500)
            at app//org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1195)
            at app//org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1175)
            at app//org.apache.parquet.hadoop.util.HadoopOutputFile.createOrOverwrite(HadoopOutputFile.java:81)
            at app//org.apache.parquet.hadoop.ParquetFileWriter.<init>(ParquetFileWriter.java:327)
            at app//org.apache.parquet.hadoop.ParquetWriter.<init>(ParquetWriter.java:292)
            at app//org.apache.parquet.hadoop.ParquetWriter$Builder.build(ParquetWriter.java:653)
            at app//org.vividus.expression.ConvertCsvToParquetFileExpressionProcessor.write(ConvertCsvToParquetFileExpressionProcessor.java:85)
            at app//org.vividus.expression.ConvertCsvToParquetFileExpressionProcessor.evaluateExpression(ConvertCsvToParquetFileExpressionProcessor.java:68)
            ... 3 more

ConvertCsvToParquetFileExpressionProcessorTests > testConvertCsvToParquetFileExpression(String) > org.vividus.expression.ConvertCsvToParquetFileExpressionProcessorTests.testConvertCsvToParquetFileExpression(String)[2] FAILED
    java.io.UncheckedIOException: Problem during file interaction:
        at app//org.vividus.expression.ConvertCsvToParquetFileExpressionProcessor.evaluateExpression(ConvertCsvToParquetFileExpressionProcessor.java:73)
        at app//org.vividus.expression.ConvertCsvToParquetFileExpressionProcessor.evaluateExpression(ConvertCsvToParquetFileExpressionProcessor.java:41)
        at app//org.vividus.expression.AbstractExpressionProcessor.execute(AbstractExpressionProcessor.java:38)
        at app//org.vividus.expression.ConvertCsvToParquetFileExpressionProcessorTests.testConvertCsvToParquetFileExpression(ConvertCsvToParquetFileExpressionProcessorTests.java:53)

        Caused by:
        ExitCodeException exitCode=-1073741515:
            at app//org.apache.hadoop.util.Shell.runCommand(Shell.java:1008)
            at app//org.apache.hadoop.util.Shell.run(Shell.java:901)
            at app//org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:1213)
            at app//org.apache.hadoop.util.Shell.execCommand(Shell.java:1307)
            at app//org.apache.hadoop.util.Shell.execCommand(Shell.java:1289)
            at app//org.apache.hadoop.fs.RawLocalFileSystem.setPermission(RawLocalFileSystem.java:978)
            at app//org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileOutputStream.<init>(RawLocalFileSystem.java:324)
            at app//org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileOutputStream.<init>(RawLocalFileSystem.java:294)
            at app//org.apache.hadoop.fs.RawLocalFileSystem.createOutputStreamWithMode(RawLocalFileSystem.java:439)
            at app//org.apache.hadoop.fs.RawLocalFileSystem.create(RawLocalFileSystem.java:428)
            at app//org.apache.hadoop.fs.RawLocalFileSystem.create(RawLocalFileSystem.java:459)
            at app//org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSOutputSummer.<init>(ChecksumFileSystem.java:433)
            at app//org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:521)
            at app//org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:500)
            at app//org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1195)
            at app//org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1175)
            at app//org.apache.parquet.hadoop.util.HadoopOutputFile.createOrOverwrite(HadoopOutputFile.java:81)
            at app//org.apache.parquet.hadoop.ParquetFileWriter.<init>(ParquetFileWriter.java:327)
            at app//org.apache.parquet.hadoop.ParquetWriter.<init>(ParquetWriter.java:292)
            at app//org.apache.parquet.hadoop.ParquetWriter$Builder.build(ParquetWriter.java:653)
            at app//org.vividus.expression.ConvertCsvToParquetFileExpressionProcessor.write(ConvertCsvToParquetFileExpressionProcessor.java:85)
            at app//org.vividus.expression.ConvertCsvToParquetFileExpressionProcessor.evaluateExpression(ConvertCsvToParquetFileExpressionProcessor.java:68)
            ... 3 more

> Task :vividus-plugin-parquet:test FAILED

> Task :vividus-plugin-rest-api:javadoc
FAILURE: Build failed with an exception.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
* What went wrong:

Execution failed for task ':vividus-plugin-parquet:test'.
```

The root cause of the issue: https://github.blog/changelog/2022-01-11-github-actions-jobs-running-on-windows-latest-are-now-running-on-windows-server-2022/

The source of `winutils.exe`: https://github.com/kontext-tech/winutils/blob/master/hadoop-3.3.1/bin/winutils.exe