Fix scope of `json-path` dependency as it's required at compilation (#6181)
Execution failed for task ':vividus-plugin-aws-secrets-manager:compileJava'.
> Compilation failed; see the compiler output below.
  /Users/runner/work/vividus/vividus/vividus-plugin-aws-secrets-manager/src/main/java/org/vividus/aws/secretsmanager/processor/AwsSecretsManagerPropertiesProcessor.java:91: error: cannot access DocumentContext
          return JsonPathUtils.getData(secretString, "$." + key);
                              ^
    class file for com.jayway.jsonpath.DocumentContext not found
  1 error